name: test

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      password:
        required: true
        type: string
      repo:
        required: true
        type: string

jobs:
  dockerize:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip build]')"
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
      -
        name: Build and push images
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          tags: ${{ inputs.repo }}:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}