name: build-prod

on:
  push:
    branches: [ 'master' ]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  dockerize:
    needs: [test]
    uses: ./.github/workflows/build.yml
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      repo: ${{ secrets.DOCKER_REPO }}

  # deploy:
  #   needs: [test, dockerize]
  #   runs-on: ubuntu-latest
  #   if: "!contains(github.event.head_commit.message, '[skip deploy]')"
  #   steps:
  #     -
  #       name: Connecting to server & Start deploy
  #       uses: appleboy/ssh-action@v0.1.2
  #       with:
  #         host: ${{secrets.SSH_HOST}}
  #         port: ${{ secrets.SSH_PORT}}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         key: ${{ secrets.SSH_KEY }}
  #         script: |
  #           "./deploy/aisha.sh"