name: test

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 17.x]

    steps:
    -
      name: Checkout latest commit
      uses: actions/checkout@v2
    -
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    -
      name: Installing Lerna
      run: npm install --global lerna
      env:
        CI: "true"
    -
      name: Bootstrapping
      run: lerna bootstrap
      env:
        CI: "true"
    -
      name: Installing dependencies
      run: npm ci
      env:
        CI: "true"
    -
      name: Show installed packages
      run: npm list --depth=0
      env:
        CI: "true"
    -
      name: Linting script
      run: npm run lint
      env:
        CI: "true"
    -
      name: Check Typescript version
      run: tsc --version
    -
      name: Build Aisha
      run: npm run build
      env:
        CI: "true"